default: &default
  adapter: postgresql
  username:
  password:
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: online_compiler_dev

test:
  <<: *default
  database: online_compiler_test

production:
  <<: *default
  database: online_compiler_prod
